### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by AlexDorozhko** [Massi-X/freepbx-phonemiddleware#10]
FreePBX 16.0.21.3, chrome 103.0.5060.114
After upgrading to version 1.3.0,  CNAME on incoming cuts to 9 digits phone number,do not apply contact name to it. (in 1.1.0 works fine, may be my misconfiguration?) Changing phone types not applying changes, contacts on carddavtoXML.php page looks like phone without limitations.  After restarting apachectl carddavtoXML.php not works, page has HTTP ERROR 500
Even reinstall module, the problem not goes. 
In apache log have next:
 PHP Fatal error:  Uncaught Error: Class 'Brick\\PhoneNumber\\PhoneNumberType' not found in /var/www/html/phoneMiddleware/helpers/phoneMiddleware.php:414\nStack trace:\n#0 /var/www/html/phoneMiddleware/carddavtoXML.php(9): phoneMiddleware->getXMLforPhones()\n#1 {main}\n  thrown in /var/www/html/phoneMiddleware/helpers/phoneMiddleware.php on line 414

Reinstall module, clear cache - but no effect(

1.2.0 seems to works after reinstall from 1.3.0

**Comment by Massi-X** [comment]
Hi and thank you for the bug report.
I'm sorry but I can't really understand what you said.

Tell me if I'm right, first you have a problem with the incoming call number that is not displayed because the number itself is cut to 9 digits, the library doesn't find a match and so no name is returned. Is this right?

Second you have a problem with the XML phonebook too, when you try to open it it returns the error above. Right?

Third when you change phone type it doesn't get applied (you don't see changes in the UI) or it doesn't work? I can't understand.

Is should point out that restarting apache is never needed.

Waiting for your answer

**Comment by AlexDorozhko** [comment]
HI. The phone number when the call is coming to the PBX comes in the format +XXXXXXXXXXXX 
But, after processing in phonemiddleware, the CNAME in the softphones looks like XXXXXXXXX, while the name of the caller is not taken from the CardDAV source. It seems that the number is cut off somewhere in the script, because no operations to change the numbers of incoming calls are performed on the PBX. My country code is UA
The second problem - well understood, the XML page stops working even after a reboot, apache restart was done to emulate  fast reload, just like after fwconsole restart.
Thirdly, in the UI, changes are visible after applying and saving, the phone type changes from "phone without limitations" to "snom phone", while there are no changes on the XML page, even after selecting "Cache duration 0 " and manually refreshing the XML page by pressing F5.

**Comment by shamrockDE** [comment]
I just recognized, that i have the first problem since version 1.3.0 too.
I've included phoneMiddleware to CID-Superfecta with regex "http://localhost/phoneMiddleware/numberToCNAM.php?number=$thenumber".
Until version 1.2.0 CID-Superfecta returned the name to a known number, since version 1.3.0 it returns the truncated number without the Country-Code.
I tried the url directly in my browser and i got the same result. Instead of the name of the known contact it returns "123456789" when i call it with the number "0049123456789".

**Comment by Massi-X** [comment]
Hi issue confirmed in every part. I'm pulling version 1.3.0 for good, will include all the enchantment+ many more things in the new version coming soon! Sorry for the inconvenience 😞

**Comment by AlexDorozhko** [comment]
Thank you for your hard work. Actually your development is very helpful!

**Comment by Massi-X** [comment]
Reopening till release
And thank you!
