### ISSUE TITLE
support more than one addressbook

### ISSUE THREAD

**Issue by mokkin** [Massi-X/freepbx-phonemiddleware#2]
**Is your feature request related to a problem? Please describe.**
Actually only one CardDAV addressbook can be entered, but usually you have several different sources.

**Describe the solution you'd like**
Add an option to add more addressbooks.

**Comment by Massi-X** [comment]
Good point, should include this in some of the new versions. Will have to look how to deal with conflicts and such

**Comment by Massi-X** [comment]
OK I'm planning on removing the two "old" libraries I'm using and substitute them with some more modern and capable. This will come with the ability to choose more than one addressbook with immediate UI response and a list dynamically created from your credentials.
Now this will work fine for one DAV URL (like now), but if you want to also be able to set multiple URLs, related to different DAV server, this is not going to be the solution you're looking for.

Could you please tell me exactly what is your need? Multiple URLS can be implemented, but I want to make sure people will use it because it obviously requires more work and is more prone to errors too.

PS. Obviously if duplicated cards are present there is no (and will never be) guarantee on which one will be the first presented to you.

**Comment by shamrockDE** [comment]
Hi, this issue is not from me, but i can tell you, how we am using our nextcloud addressbooks. 
I have only one nextcloud installation for our contacts (family), but i have created several addressbooks there. Everyone has one personal addressbooks and we have shared addressbooks with contacts for all.
So my use case is to include serveral addressbooks from one nextcloud-user  at one nextcloud installation via one DAV URL.

**Comment by Massi-X** [comment]
Thank you for te feedback @shamrockDE this is exactly what I'm about to implement! I need some time, tis will be a big update 😉

**Comment by Massi-X** [comment]
Fixed with version 2.0.0. Downloads moved [here](https://phonemiddleware.000webhostapp.com/releases/)
